# Generated by Django 5.2.12 on 2026-03-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
